spring:
  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin


server:
  port: 8090